// Login Component
export const LOGIN_VISIBLE_ACTION = 'LOGIN_VISIBLE_ACTION';

// Signup Component
export const SIGNUP = 'SIGNUP';
export const UPDATE_SIGNUP_INPUTS = 'UPDATE_SIGNUP_INPUTS';
export const CLEAR_SIGNUP_INPUT_FIELDS = 'CLEAR_SIGNUP_INPUT_FIELDS';
export const SIGNUP_LOADER_STATUS = 'SIGNUP_LOADER_STATUS'

// Login Component
export const LOGIN = 'LOGIN';
export const UPDATE_LOGIN_INPUTS = 'UPDATE_LOGIN_INPUTS';
export const CLEAR_LOGIN_INPUT_FIELDS = 'CLEAR_LOGIN_INPUT_FIELDS';
export const LOGIN_LOADER_STATUS = 'LOGIN_LOADER_STATUS'