// LeftNavBar Component
export const DIRECT_MESSAGES_DATA = 'DIRECT_MESSAGES_DATA';
export const CHANNELS_DATA = 'CHANNELS_DATA';
export const HIGHLIGHT_SELECTED_CHAT = 'HIGHLIGHT_SELECTED_CHAT';

// List Component
export const LIST_DATA = 'LIST_DATA';
export const CLEAR_LIST_DATA = 'CLEAR_LIST_DATA';
export const MEMBERS_TO_BE_ADDED_LIST_DATA = 'MEMBERS_TO_BE_ADDED_LIST_DATA';

// Loader Component
export const FULL_SCREEN_LOADER_VISIBILITY = 'FULL_SCREEN_LOADER_VISIBILITY';

// Login Component
export const CLEAR_LOGIN_INPUT_FIELDS = 'CLEAR_LOGIN_INPUT_FIELDS';
export const LOGIN_LOADER_STATUS = 'LOGIN_LOADER_STATUS'
export const LOGIN_VISIBLE_ACTION = 'LOGIN_VISIBLE_ACTION';
export const UPDATE_LOGIN_INPUTS = 'UPDATE_LOGIN_INPUTS';

// Modal Component
export const DIRECT_MESSAGE_SEARCH_RESULT = 'DIRECT_MESSAGE_SEARCH_RESULT';
export const UPDATE_DIRECT_MESSAGE_INPUTS = 'UPDATE_DIRECT_MESSAGE_INPUTS';
export const RESET_MODAL_STATE = 'RESET_MODAL_STATE';
export const DIRECT_MESSAGE_BUTTON_LOADER_STATUS = 'DIRECT_MESSAGE_BUTTON_LOADER_STATUS';
export const DIRECT_MESSAGE_DATA_LOADER_STATUS = 'DIRECT_MESSAGE_DATA_LOADER_STATUS';
export const DIRECT_MESSAGE_MODAL_VISIBILITY = 'DIRECT_MESSAGE_MODAL_VISIBILITY';
export const DIRECT_MESSAGE_MEMBERS_TO_BE_DISPLAYED = 'DIRECT_MESSAGE_MEMBERS_TO_BE_DISPLAYED';

// Signup Component
export const UPDATE_SIGNUP_INPUTS = 'UPDATE_SIGNUP_INPUTS';
export const CLEAR_SIGNUP_INPUT_FIELDS = 'CLEAR_SIGNUP_INPUT_FIELDS';
export const SIGNUP_LOADER_STATUS = 'SIGNUP_LOADER_STATUS'

// Chat Component
export const CHAT_LOADER_STATUS = 'CHAT_LOADER_STATUS';
export const CHAT_MESSAGES_DATA = 'CHAT_MESSAGES_DATA';
export const SCROLL_TO_BOTTOM = 'SCROLL_TO_BOTTOM';
export const UPDATE_NEW_MESSAGE_INPUT = 'UPDATE_NEW_MESSAGE_INPUT';
export const APPEND_NEW_CHAT_MESSAGES_DATA = 'APPEND_NEW_CHAT_MESSAGES_DATA';
export const MARK_NEW_CHAT_MESSAGE_SENT = 'MARK_NEW_CHAT_MESSAGE_SENT';

