// Login Component
export const LOGIN_VISIBLE_ACTION = 'LOGIN_VISIBLE_ACTION';

// Signup Component
export const UPDATE_SIGNUP_INPUTS = 'UPDATE_SIGNUP_INPUTS';
export const CLEAR_SIGNUP_INPUT_FIELDS = 'CLEAR_SIGNUP_INPUT_FIELDS';
export const SIGNUP_LOADER_STATUS = 'SIGNUP_LOADER_STATUS'

// Login Component
export const UPDATE_LOGIN_INPUTS = 'UPDATE_LOGIN_INPUTS';
export const CLEAR_LOGIN_INPUT_FIELDS = 'CLEAR_LOGIN_INPUT_FIELDS';
export const LOGIN_LOADER_STATUS = 'LOGIN_LOADER_STATUS'

// Modal Component
export const DIRECT_MESSAGE_SEARCH_RESULT = 'DIRECT_MESSAGE_SEARCH_RESULT';
export const UPDATE_DIRECT_MESSAGE_INPUTS = 'UPDATE_DIRECT_MESSAGE_INPUTS';
export const CLEAR_DIRECT_MESSAGE_INPUTS = 'CLEAR_DIRECT_MESSAGE_INPUTS';
export const DIRECT_MESSAGE_BUTTON_LOADER_STATUS = 'DIRECT_MESSAGE_BUTTON_LOADER_STATUS';
export const DIRECT_MESSAGE_DATA_LOADER_STATUS = 'DIRECT_MESSAGE_DATA_LOADER_STATUS';
export const DIRECT_MESSAGE_MODAL_VISIBILITY = 'DIRECT_MESSAGE_MODAL_VISIBILITY';
export const DIRECT_MESSAGE_MEMBERS_TO_BE_DISPLAYED = 'DIRECT_MESSAGE_MEMBERS_TO_BE_DISPLAYED';

// List Component
export const LIST_DATA = 'LIST_DATA';
export const CLEAR_LIST_DATA = 'CLEAR_LIST_DATA';
export const MEMBERS_TO_BE_ADDED_LIST_DATA = 'MEMBERS_TO_BE_ADDED_LIST_DATA';